### ISSUE TITLE
Bug 🐞: Unexpected input: path & Release Version

### ISSUE THREAD

**Issue by phanlezz** [rasmus-saks/release-a-changelog-action#3]
## Bug: GitHub does not recognize path as a valid input

The GitHub action displays a warning about the input parameter `path`. But the created release still has the correct changelog entries as description. (see screenshot)

![grafik](https://github.com/rasmus-saks/release-a-changelog-action/assets/65733509/3ffa0fb5-bf65-40db-9c67-dfe38cb30da3)
![release-post](https://github.com/rasmus-saks/release-a-changelog-action/assets/65733509/1fcb1d33-96b6-4f35-8032-5ea8082d8afb)

There is also a second "problem". 

If I have understood correctly, the name in square brackets in the changelog is assumed for the release 'tag'. In our case, however, the release 'tag' and the version in the changelog are different. We use standard version numbers (major.minor.path) for the releases in NPM, docker, Gradle, and in the changelogs, but a prefix version for the tag in GitHub. 
The creation of the corresponding prefix tag triggers the release of one of the sub-repos. 
Would it be possible to implement a feature so that in addition to the current behavior either:
- the last generated tag is used
- the tag name to be used or created is passed as a parameter

If possible, it would be great if there was an input field to pass the title of the release post. What is currently the version number, so that you can pass additional customized information.

> In this screenshot you can see, that the next action failed to attach the assets to the release presumably because it couldn't find a release for the tag that triggerd the action.

![grafik](https://github.com/rasmus-saks/release-a-changelog-action/assets/65733509/c391262c-2c00-4216-9729-1696706653f7)

> I'm very sorry to bother you again, but the latest release in our repo didn't work, and I dont want to remove this action, so that we have to do the post content manually again.

**Comment by rasmus-saks** [comment]
Sorry about the broken release and again I appreciate the detailed bug report!

I've released `v1.2.0` which should hopefully address everything you've mentioned here:
- Fixed `Unexpected input(s) 'path'`
- Added `title-template` and `tag-template` inputs to support multi-project repos (check the readme for instructions)

Let me know if that works for you 🙂

**Comment by phanlezz** [comment]
Everything worked as intended. Thanks again for the quick help! 🥇

**Comment by rasmus-saks** [comment]
Excellent, great to hear!
